### ISSUE TITLE
WithDependencies1.0.1で録画機能が動かない

### ISSUE THREAD

**Issue by CaffeineUnion** [wakapippi/VRMAnimationClip#1]
![image](https://user-images.githubusercontent.com/106811951/230825206-ec73e247-f6bd-4013-8fd3-828e313cd9bc.png)

1.0.1のWithDependencies1.0.1.unitypackageを読み込んだところ、画像のような状態になり録画ができません。
OriginalCodeOnly1.0.1.unitypackageと依存ファイルを別で読み込んだ場合は、VRMAnimationClipRecorderのみグレーアウトされます。

現時点では録画用プロジェクトに1.0、ビルドして再生する用のプロジェクトに1.0.1を導入する形で解決しています。

**Comment by wakapippi** [comment]
Editorスクリプトの扱いに問題がありそうなので、一旦1.0.1の変更をRevertさせていただきます
本対応はまた後ほど行います

**Comment by wakapippi** [comment]
1.0.2にて修正いたしました
